### ISSUE TITLE
Not an issue just want to say thank you

### ISSUE THREAD

**Issue by tibudiyanto** [SuspiciousLookingOwl/saweria-api#1]
Sorry for opening an issue but I just want to say this is very neat. I am one of the guy behind saweria and it just cool to see this in the wild. 

Lmk if you have questions, bug report or anything.

Cheers

**Comment by SuspiciousLookingOwl** [comment]
You're welcome! Glad you guys are cool with me publishing this package.

I'll let you know if I found any bugs.
