### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by NotHaxJustChill** [SuspiciousLookingOwl/saweria-api#4]
Its totally fine before, but then today i got Error 403. so i tried to change .login to .setStreamKey but still error 403.

``` 
(node:7180) UnhandledPromiseRejectionWarning: Error: Request failed with status code 403
    at createError (D:\Project\Unknown\node_modules\axios\lib\core\createError.js:16:15)
    at settle (D:\Project\Unknown\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (D:\Project\Unknown\node_modules\axios\lib\adapters\http.js:244:11)
    at IncomingMessage.emit (events.js:387:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7180) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, 
use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:7180) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by SuspiciousLookingOwl** [comment]
Can confirm this, seems like the request is being blocked by Cloudflare, I will take a look for the workaround

**Comment by SuspiciousLookingOwl** [comment]
Any idea @tibudiyanto ? lol

**Comment by tibudiyanto** [comment]
Probably rate limited? your user agent might be too fishy for cloudflare too.

**Comment by SuspiciousLookingOwl** [comment]
I don't think so, I imposed the API request using Postman just like how the browser send the request (exactly the same headers), and it's being rejected by Cloudflare somehow lol. Maybe it's just Cloudflare being Cloudflare

Lets see if this fixes itself tomorrow

**Comment by NotHaxJustChill** [comment]
still error

**Comment by SuspiciousLookingOwl** [comment]
I still don't know how to fix this, sending request manually like this
```js
const response = await fetch("https://api.saweria.co/users", {
    method: "GET"
});

console.log(await response.text());
```
works fine on browser's console, but not on Node / Postman, using VPN doesn't solve the issue, Not really sure what's going on here

**Comment by SuspiciousLookingOwl** [comment]
My final assumption is Saweria's API and events endpoint are being protected by Cloudflare, and Cloudflare attempted to do a "browser check" (to make sure that the request is being sent by a user within browser / not automated), and requires browser with JavaScript to do the check (like captcha), hence why CloudFlare is responding with 403.

Any chance to loosen the Cloudflare protection on api endpoint (`api.saweria.co` and  `events.saweria.co`) from Saweria's end @tibudiyanto?

If not, I'm afraid that I need to deprecate this library as it will no longer work.

**Comment by damarsimple** [comment]
i dont know if this helping or not. 
but i managed to make the websocket client working by making custom chrome extensions
![Screenshot 2021-08-31 235457](https://user-images.githubusercontent.com/10891460/131544477-bee4c297-4111-4b76-b398-ba431972a212.jpg)

**Comment by blek-id** [comment]
any chance that saweria will eventually disable BIC on api calls? it's a bummer to see a library this useful get deprecated...

**Comment by tibudiyanto** [comment]
hey y'all, may I understand the usecase of using saweria's api? 

We are very close to releasing a webhook feature. This feature will enable you to supply a public endpoint and saweria will hit that endpoint on every tip / donation made to your account.

Let us know if you want to try this feature.

ref: https://www.evilfactorylabs.org/faultable/mengenal-dan-mengapa-menggunakan-function-as-a-service-faas-1c4c

**Comment by damarsimple** [comment]
@tibudiyanto my usecase is to listening to donation made by people and send command to minecraft server through php app

(minecraft donation challenge)

**Comment by SuspiciousLookingOwl** [comment]
> hey y'all, may I understand the usecase of using saweria's api?
> 
> We are very close to releasing a webhook feature. This feature will enable you to supply a public endpoint and saweria will hit that endpoint on every tip / donation made to your account.
> 
> Let us know if you want to try this feature.
> 
> ref: https://www.evilfactorylabs.org/faultable/mengenal-dan-mengapa-menggunakan-function-as-a-service-faas-1c4c

I think most of us just want to listen to donation event, but having the flexibility to be able to develop anything we want would be nice 😛

But are you saying that you aren't planning to loosen the Cloudflare protection for the API endpoint?

> i dont know if this helping or not.
> but i managed to make the websocket client working by making custom chrome extensions
> ![Screenshot 2021-08-31 235457](https://user-images.githubusercontent.com/10891460/131544477-bee4c297-4111-4b76-b398-ba431972a212.jpg)

Sending the request from the browser is expected to be working

**Comment by JeyyGit** [comment]
I have the same problem while tempting to login and got 403 response status 
![image](https://user-images.githubusercontent.com/20415821/132151999-4c1e2a0c-e3f5-4b69-8d0e-7bd93bedb7df.png)

**Comment by tibudiyanto** [comment]
>
>
> any chance that saweria will eventually disable BIC on api calls? it's a bummer to see a library this useful get deprecated...

I think blek-id has tried our callback API and it seems it serves his usecase really well (minecraft server).

With that being said:

> 
> 
> @tibudiyanto my usecase is to listening to donation made by people and send command to minecraft server through php app
> 
> (minecraft donation challenge)


@damarsimple  let me know if you want to try the callback feature too. 


> I think most of us just want to listen to donation event, but having the flexibility to be able to develop anything we want would be nice 😛
> 
> But are you saying that you aren't planning to loosen the Cloudflare protection for the API endpoint?


Probably we'll disable it back soonish. Reason why we are doing it in the first place: we are seeing lots of people abusing the API by hitting our endpoint hundreds time per seconds. 

Going forward, the only supported way to subscribe to tip events is via the callback.

**Comment by SuspiciousLookingOwl** [comment]
> Probably we'll disable it back soonish. Reason why we are doing it in the first place: we are seeing lots of people abusing the API by hitting our endpoint hundreds time per seconds.

If that's the case, I think it makes more sense to do something on the backend (e.g. rate limiting ) instead of doing a BIC, because nothing stopping user with malicious intent from sending scripted requests via browser's console, or using a headless browser like puppeteer.

**Comment by SuspiciousLookingOwl** [comment]
Since seems like Saweria won't disable Cloudflare's BIC, I will mark this library as deprecated since it won't work anymore.

Btw if you are using Saweria's Webhook and Express for the backend, I made a simple Express middleware to validate Saweria Webhook Request, it's called [saweria-webook-express](https://github.com/SuspiciousLookingOwl/saweria-webhook-express)

**Comment by SuspiciousLookingOwl** [comment]
Just realized that this can be used for (local) web based applications, like Chrome Extension or (possibly) Electron 😅 

So I will keep maintaining this library (because I'm going to use this for a chrome extension that I'm current developing), but testing is gonna be pain in the butt.
